name: Docker Validate

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:

      # Faz login no Docker Hub utilizando os secrets configurados no repositório
      # Isso permite fazer pull de imagens privadas e autenticar corretamente
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Usuário do Docker Hub
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Token (senha segura)

      # Baixa a imagem do Docker Hub utilizando o nome e a tag informados
      # Isso garante que a imagem enviada anteriormente está acessível
      - name: Pull da imagem
        run: |
          docker pull "${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}"

      # Executa o container baseado na imagem baixada
      # -d roda em modo "detached" (em segundo plano)
      # --name define um nome fixo para facilitar validação
      # -p 3000:3000 expõe a porta da aplicação
      - name: Rodar container
        run: |
          docker run -d \
            --name teste-container \
            -p 3000:3000 \
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}"

          # Aguarda alguns segundos para dar tempo da aplicação iniciar
          sleep 15

      # Verifica se o container realmente está rodando
      # Se não estiver, exibe logs e força erro na pipeline (exit 1)
      - name: Validar container
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' teste-container)" != "true" ]; then
            echo "Erro ao subir container"
            docker logs teste-container || true
            exit 1
          fi

          # Caso esteja rodando, imprime mensagem de sucesso
          echo "Container rodando com sucesso"

          echo "Testando aplicação com curl..."

          response=$(curl -s -o /dev/stderr -w "%{http_code}" http://localhost:3000)

          echo ""
          echo "Status HTTP: $response"

          if [ "$response" -ne 200 ]; then
            echo "Erro: aplicação não respondeu com 200"
            docker logs teste-container || true
            exit 1
          fi

          echo "Aplicação respondeu corretamente  "

      # Sempre executa (mesmo se der erro antes)
      # Responsável por parar e remover o container de teste
      - name: Limpar container
        if: always()
        run: |
          docker stop teste-container || true
          docker rm teste-container || true