# Nome do workflow reutilizável
name: executador-de-templates

# Permite que esse workflow seja chamado por outro workflow
on:
  workflow_call:
    inputs: # Define os inputs que esse workflow espera receber
      STACK_TYPE: # Tipo da aplicação (next ou react)
        required: true # Obrigatório receber esse valor
        type: string   # Tipo do 
      version: # Versão do Node.js a ser usada nos builds
        required: false
        type: string
    secrets: 
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:

  #  Job 1: verifica se a branch está sincronizada com a main
  check-sync:
    # Chama outro workflow reutilizável (template)
    uses: mateus0507/pipeline-templates/.github/workflows/check-main-sync.yaml@main

  #  Job 4: build Docker para Next.js
  docker-build:
    needs: [check-sync] # Só roda se o build do Next terminar
    if: ${{ inputs.STACK_TYPE == 'next' || inputs.STACK_TYPE == 'react' }}
    uses: mateus0507/pipeline-templates/.github/workflows/nixpacks-build.yaml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: ${{ inputs.STACK_TYPE }}-app # Nome da imagem Docker
      context_dir: .    # Diretório base do build (raiz do projeto)
      version: ${{ inputs.version || '22' }}


  validate-structure:
    needs: [docker-build]
    uses: mateus0507/pipeline-templates/.github/workflows/validate-structure.yaml@main

  deploy-k8s:
    needs: [validate-structure]
    uses: mateus0507/pipeline-templates/.github/workflows/k8s-deploy.yaml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      image_name: ${{ inputs.STACK_TYPE }}-app:${{ github.sha }}
      deployment_name: minha-app
      container_name: minha-app
      manifests_path: ./k8s

  validate-k8s:
    needs: [deploy-k8s]
    uses: mateus0507/pipeline-templates/.github/workflows/k8s-validate.yaml@main
    with:
      deployment_name: minha-app
      namespace: default

  # docker-builder-gcp:
  #   needs: [check-sync]
  #   uses: mateus0507/pipeline-templates/.github/workflows/docker-build-gcp.yaml@main

  #   with:
  #     image_name: minha-app
  #     project_id: meu-projeto-gcp
  #     region: us-central1
  #     repository: minhas-imagens

  #   secrets:
  #     GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  # docker-validate-next:
  #   needs: [docker-build]
  #   if: ${{ inputs.STACK_TYPE == 'next' || inputs.STACK_TYPE == 'react' }}
  #   uses: mateus0507/pipeline-templates/.github/workflows/docker-validate.yaml@main
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  #   with:
  #     image_name: ${{ inputs.STACK_TYPE }}-app
  #     tag: ${{ github.sha }}