# Nome do workflow reutilizável
name: executador-de-templates

# Permite que esse workflow seja chamado por outro workflow
on:
  workflow_call:
    inputs: # Define os inputs que esse workflow espera receber
      STACK_TYPE: # Tipo da aplicação (next ou react)
        required: true # Obrigatório receber esse valor
        type: string   # Tipo do 
      version: # Versão do Node.js a ser usada nos builds
        required: false
        type: string

jobs:

  #  Job 1: verifica se a branch está sincronizada com a main
  check-sync:
    # Chama outro workflow reutilizável (template)
    uses: mateus0507/pipeline-templates/.github/workflows/check-main-sync.yaml@main

  #  Job 2: build do Next.js (só roda se STACK_TYPE = next)
  next-build:
    needs: [check-sync] # Só executa depois do check-sync
    if: ${{ inputs.STACK_TYPE == 'next' }} # Condição baseada no input recebido
    uses: mateus0507/pipeline-templates/.github/workflows/next-build.yaml@main
    with:
      node_version: ${{ inputs.version || '22' }} # Parâmetro enviado para o template

  #  Job 3: build do React (só roda se STACK_TYPE = react)
  react-build:
    needs: [check-sync]
    if: ${{ inputs.STACK_TYPE == 'react' }}
    uses: mateus0507/pipeline-templates/.github/workflows/react-build.yaml@main
    with:
      node_version: ${{ inputs.version || '22' }}

  #  Job 4: build Docker para Next.js
  docker-build-next:
    needs: [next-build] # Só roda se o build do Next terminar
    if: ${{ inputs.STACK_TYPE == 'next' }}
    uses: mateus0507/pipeline-templates/.github/workflows/nixpacks-build.yaml@main
    with:
      image_name: next-app # Nome da imagem Docker
      context_dir: .       # Diretório base do build (raiz do projeto)
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  #  Job 5: build Docker para React
  docker-build-react:
    needs: [react-build]
    if: ${{ inputs.STACK_TYPE == 'react' }}
    uses: mateus0507/pipeline-templates/.github/workflows/nixpacks-build.yaml@main
    with:
      image_name: react-app
      context_dir: .
      #é pra rodar na versão 22
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}