name: Validate Kubernetes

on:
  workflow_call:
    inputs:
      deployment_name:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: default

jobs:
  validate:
    runs-on: self-hosted

    steps:
      - name: Verificar cluster
        run: kubectl cluster-info

      - name: Validar rollout do deployment
        run: kubectl rollout status deployment/${{ inputs.deployment_name }} --namespace=${{ inputs.namespace }}

      - name: Listar deployments
        if: always()
        run: kubectl get deployments -n ${{ inputs.namespace }}

      - name: Listar pods
        if: always()
        run: kubectl get pods -o wide -n ${{ inputs.namespace }}

      - name: Listar services
        if: always()
        run: kubectl get svc -n ${{ inputs.namespace }}

      - name: Descrever deployment
        if: always()
        run: kubectl describe deployment ${{ inputs.deployment_name }} -n ${{ inputs.namespace }}

      - name: Descrever primeiro pod
        if: always()
        shell: powershell
        run: |
          $pod = kubectl get pods -n ${{ inputs.namespace }} -o jsonpath="{.items[0].metadata.name}"
          Write-Host "Pod encontrado: $pod"
          kubectl describe pod $pod -n ${{ inputs.namespace }}

      - name: Logs do primeiro pod
        if: always()
        shell: powershell
        run: |
          $pod = kubectl get pods -n ${{ inputs.namespace }} -o jsonpath="{.items[0].metadata.name}"
          Write-Host "Pod encontrado: $pod"
          kubectl logs $pod -n ${{ inputs.namespace }}