name: Deploy Kubernetes

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      deployment_name:
        required: true
        type: string
      container_name:
        required: true
        type: string
      manifests_path:
        required: false
        type: string
        default: ./k8s

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar kubectl
        run: kubectl version --client

      - name: Verificar cluster
        run: kubectl cluster-info

      - name: Aplicar manifestos
        run: |
          kubectl apply -f ${{ inputs.manifests_path }}/deployment.yaml
          kubectl apply -f ${{ inputs.manifests_path }}/service.yaml

      - name: Atualizar imagem do deployment
        run: kubectl set image deployment/${{ inputs.deployment_name }} ${{ inputs.container_name }}=${{ inputs.image_name }}

      - name: Mostrar recursos
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get svc