name: Next build

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: "20"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Instalar dependências
        run: npm ci

      - name: Gerar build da aplicação
        run: npm run build