# Nome do workflow reutilizável
# Esse template é responsável por gerar uma imagem Docker usando Nixpacks
name: Nixpacks build

on:
  workflow_call:
    inputs:

      image_name:
        required: false
        type: string

      context_dir:
        required: false
        type: string
        default: .

      version:
        required: false
        type: string
        
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  nixpacks-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Nixpacks
        shell: bash
        run: |
          curl -fsSL https://nixpacks.com/install.sh | bash
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Gerar imagem com Nixpacks
        shell: bash
        run: |
          set -euo pipefail

          nixpacks build "${{ inputs.context_dir }}" \
            --env NIXPACKS_NODE_VERSION="${{ inputs.version }}" \
            --tag "${{ inputs.image_name }}:${{ github.sha }}"

      # 👇 NOVO: login no Docker Hub
      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 👇 NOVO: tag da imagem no formato do Docker Hub
      - name: Tag da imagem
        run: |
          docker tag \
          ${{ inputs.image_name }}:${{ github.sha }} \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ github.sha }}

      # 👇 NOVO: envio da imagem
      - name: Push da imagem
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ github.sha }}